Drop quay.io
modcluster/mod_proxy_cluster pull request #127
Opened 2023-08-08 11:22 UTC by jajik

close #125

2023-08-08 13:02 UTC, rhusar requested changes
Looks good but the names are off.

I would drop the "-local" suffix, that's unnecessary. Also, any image can be made not local by pushing it remotely. Also "-image" is unnecessary - the parameter for docker run is an image name. But more importantly, the names are not unique enough - think about what these are for - they are for testing mod_proxy_cluster and they are products of the testsuite. So how about "mod_proxy_cluster-testsuite-tomcat-10.0" and analogous.

2023-08-08 13:03 UTC, rhusar commented on test/README.md
> +By default local `httpd-local` and `tomcat-local` images are used. You can control the names by setting `IMG` and `HTTPD_IMG`
Drop the -local.

2023-08-08 13:03 UTC, rhusar commented on test/httpd/README.md
> +docker build -t httpd-image .
Drop the -image suffice.

2023-08-08 13:03 UTC, rhusar commented on test/testsuite.sh
> +    export HTTPD_IMG=httpd-local
And here.

2023-08-08 13:45 UTC, jajik commented
Point taken. Let's change that if we ever get to that point. :)

2023-08-08 13:47 UTC, rhusar commented
> Point taken. Let's change that if we ever get to that point. :)

👍🏼  Agreed.

2023-08-09 15:59 UTC, merged

2023-08-09 15:59 UTC, rhusar commented
Merged, thanks @jajik