test: Add option to change tomcat conf files
modcluster/mod_proxy_cluster pull request #142
Opened 2023-09-19 08:43 UTC by jajik

Adresses #141. Introduces two variables for server.xml and context.xml by which you can control which files will be used. This does not introduces separate files for each supported version as it is not needed now.

2023-09-26 12:33 UTC, jfclere approved these changes

2023-09-26 12:44 UTC, rhusar requested changes
While this works, I had more of an idea to copy a whole directory overlay (so we can customize anything we want tomcat specific without adding special support for all configuration files we want to override) and have source files in directories like /tomcat-8.5, /tomcat-10.1, etc. WDYT?

2023-09-26 13:09 UTC, jajik commented
I don't think it's necessary right now. Are we planning to create different configurations for every tomcat? If not, I think the less files we have to keep track of the better. (And it also prevents config to differ unnecessarily across different versions.)

With that said, I can imagine directories `8.5`, 9.0`, etc. under `test/tomcat/`, that would be clean imo. But it's up to you two, I'll accommodate. :)

2023-10-03 09:44 UTC, jfclere commented
@rhusar probably we can do the over stuff in another PR/

2023-10-03 12:47 UTC, rhusar approved these changes

2023-10-03 12:47 UTC, merged

2023-10-03 12:47 UTC, rhusar commented
> @rhusar probably we can do the over stuff in another PR/

Sure, we can do this later.

2023-10-03 12:48 UTC, rhusar commented
Merged, thanks @jajik and @jfclere