Update the main README, remove native/README
modcluster/mod_proxy_cluster pull request #209
Opened 2024-03-05 08:56 UTC by jajik

close #206 

Summary: 
* dependencies of dependencies were dropped from the tools list
* native/README.md was removed – we have it in our docs properly updated
* link added for the doxygen docs online

2024-03-05 08:59 UTC, jajik commented
I left `test/README.md` as is, we do not have a section for it on the website and it looks up-to-date.

2024-03-05 10:36 UTC, rhusar requested changes
Looks good, just a nitpick.

2024-03-05 10:36 UTC, rhusar commented on README.md
> +### Doxygen api docs
s/api/API

2024-03-05 10:38 UTC, jajik commented on README.md
> +### Doxygen api docs
Fixed, thanks.

2024-03-06 14:31 UTC, rhusar approved these changes
LGTM now.

2024-03-06 14:31 UTC, jajik commented
(rebase)

2024-03-06 14:32 UTC, merged

2024-03-06 14:32 UTC, rhusar commented
Not really needed as this doesn't affect the tests (but we don't do conditional CI).

2024-03-06 14:32 UTC, rhusar commented
Thanks @jajik

2024-03-06 14:34 UTC, jajik commented
> Not really needed as this doesn't affect the tests (but we don't do conditional CI).

It depends on who's merging :smile: 

Thanks for the review & merge.

2024-03-06 15:12 UTC, rhusar commented
> > Not really needed as this doesn't affect the tests (but we don't do conditional CI).
> 
> It depends on who's merging 😄

haha, true, maybe we should reconsider that requirement to be up to date..