Require Alias and Context for *-APP commands
modcluster/mod_proxy_cluster pull request #288
Opened 2024-10-09 16:03 UTC by jajik

https://issues.redhat.com/browse/MODCLUSTER-832

2024-10-10 08:01 UTC, jajik commented
Converting to draft because it does make sense to have some APP commands global... have to sort it out...

2024-10-11 08:12 UTC, rhusar requested changes

2024-10-11 08:12 UTC, rhusar commented on native/mod_manager/mod_manager.c
> +    /* Note: This applies only for non-wildcared requests for which Alias and Context are required */
What is 'wildcared'? :)

2024-10-11 08:56 UTC, jajik commented on native/mod_manager/mod_manager.c
> +    /* Note: This applies only for non-wildcared requests for which Alias and Context are required */
Good catch, should be ok now.

2024-10-12 10:20 UTC, rhusar commented on native/mod_manager/mod_manager.c
> +    /* Note: This applies only for non-wildcared requests for which Alias and Context are required */
Haha, thanks

2024-10-15 12:18 UTC, rhusar commented
@jajik Can you remind me what are the implications of mod_proxy_cluster creating an empty Virtual Host (with empty Context and Alias)?

2024-10-24 08:51 UTC, jfclere approved these changes

2024-10-24 13:38 UTC, jajik commented
@rhusar could you please remove your *changes requested* if there is nothing else?

2024-10-24 17:34 UTC, merged

2024-10-24 17:34 UTC, rhusar commented
Thanks @jajik and @jfclere