Use podman instead of docker in tests
modcluster/mod_proxy_cluster pull request #95
Opened 2023-06-02 11:58 UTC by jajik

2023-06-02 13:59 UTC, jfclere requested changes

2023-06-02 14:20 UTC, jajik commented on test/native/tests.sh
> -    while true
Oh, now I get the intention. But then there should not be the `-a` argument for `podman ps`, I think...

2023-06-02 14:58 UTC, rhusar requested changes
Please let's NOT do this - make the container binary switchable / configurable / autodetected.

Instead of this you could just update the readme to to install podman-docker package or hell, run 'alias docker=podman'

2023-06-05 06:29 UTC, jajik commented
> Please let's NOT do this - make the container binary switchable / configurable / autodetected.
> 
> Instead of this you could just update the readme to to install podman-docker package or hell, run 'alias docker=podman'

Personally, I don't think the change is necessary – previously, the podman was used for the httpd's image, docker for tomcat. However, with the latest changes (9096b14f1c94be6f08aebe4e642a7e267ade67f6, e4422b6dd9c6d7255cf2d6f0ce422b127c7c3709) the tests are broken and we should address it. (The second commit suggest that we want to move to podman, hence this PR.)

2023-06-05 10:16 UTC, rhusar commented
> > Please let's NOT do this - make the container binary switchable / configurable / autodetected.
> > Instead of this you could just update the readme to to install podman-docker package or hell, run 'alias docker=podman'
> 
> Personally, I don't think the change is necessary – previously, the podman was used for the httpd's image, docker for tomcat. However, with the latest changes ([9096b14](https://github.com/modcluster/mod_proxy_cluster/commit/9096b14f1c94be6f08aebe4e642a7e267ade67f6), [e4422b6](https://github.com/modcluster/mod_proxy_cluster/commit/e4422b6dd9c6d7255cf2d6f0ce422b127c7c3709)) the tests are broken and we should address it. (The second commit suggest that we want to move to podman, hence this PR.)

Yeah, these went in without a pull request - it looks like @jfclere accidentally pushed directly to the branch so this was missed in review.

2023-06-06 17:07 UTC, jajik commented
I changed the podman to docker as agreed. Also, I made a few changes to tests. It seems that the previously introduced changes are causing issues when tests are re-run; one has to be sure that everything from the previous run is cleaned up (tests are now faster so it seems like a reasonable trade off until we rework the tests in the future).

2023-06-08 11:05 UTC, rhusar approved these changes
LGTM now.

2023-06-08 11:06 UTC, merged